<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18241" started-at="2020-08-25T23:20:07Z" finished-at="2020-08-25T23:20:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18241" started-at="2020-08-25T23:20:07Z" finished-at="2020-08-25T23:20:25Z">
      <class name="Tests.Login.Test_LoginValid">
        <test-method status="PASS" signature="TestSetUp()[pri:0, instance:Tests.Login.Test_LoginValid@204f30ec]" name="TestSetUp" is-config="true" duration-ms="8651" started-at="2020-08-25T23:20:07Z" finished-at="2020-08-25T23:20:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSetUp -->
        <test-method status="FAIL" signature="TestLogin()[pri:0, instance:Tests.Login.Test_LoginValid@204f30ec]" name="TestLogin" duration-ms="1694" started-at="2020-08-25T23:20:16Z" finished-at="2020-08-25T23:20:17Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at java.util.Objects.requireNonNull(Unknown Source)
at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:106)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:85)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:45)
at Pages.Login.PageFactory.setUserName(PageFactory.java:47)
at Tests.Login.Test_LoginValid.doAValidLogin(Test_LoginValid.java:43)
at Tests.Login.Test_LoginValid.TestLogin(Test_LoginValid.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLogin -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Tests.Login.Test_LoginValid@204f30ec]" name="afterTest" is-config="true" duration-ms="7831" started-at="2020-08-25T23:20:17Z" finished-at="2020-08-25T23:20:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Tests.Login.Test_LoginValid -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
